/* tslint:disable */
/* eslint-disable */
/**
 * DocShareApi | v1
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface CommentDto {
    'id': SearchCommentsParentIdParameter;
    'content': string | null;
    'parentId': CommentDtoParentId | null;
    'documentId': string;
    'authorId': string | null;
    'authorName': string | null;
    'hasChildren': boolean;
    'isDevelopmentComment': boolean;
    'createdOn': string;
}
export interface CommentDtoParentId {
}
export interface CreateCommentDto {
    'content': string;
    'parentId': CommentDtoParentId | null;
    'documentId': string;
}
export interface CreateUpdateDocDto {
    'title': string;
    'description': string;
    'tags': Array<string>;
    'roles': { [key: string]: UserDevRole; };
}
export interface DocumentDto {
    'id': string;
    'title': string;
    'description': string;
    'createdOn': string;
    'ownerName': string;
    'tags': Array<string>;
    'userNamesToRoles': { [key: string]: UserDevRole; };
}
export interface ExceptionDto {
    'code': string;
    'description': string;
    'details': Array<string> | null;
}
export interface LoginDto {
    'userNameOrEmail': string;
    'password': string;
}
export interface PaginatedResponseDtoOfCommentDto {
    'items': Array<CommentDto>;
    'totalItems': PaginatedResponseDtoOfCommentDtoTotalItems;
    'totalPages': PaginatedResponseDtoOfCommentDtoTotalItems;
    'currentPage': PaginatedResponseDtoOfCommentDtoTotalItems;
    'pageSize': PaginatedResponseDtoOfCommentDtoTotalItems;
}
export interface PaginatedResponseDtoOfCommentDtoTotalItems {
}
export interface PaginatedResponseDtoOfDocumentDto {
    'items': Array<DocumentDto>;
    'totalItems': PaginatedResponseDtoOfCommentDtoTotalItems;
    'totalPages': PaginatedResponseDtoOfCommentDtoTotalItems;
    'currentPage': PaginatedResponseDtoOfCommentDtoTotalItems;
    'pageSize': PaginatedResponseDtoOfCommentDtoTotalItems;
}
export interface PaginatedResponseDtoOfUserWithoutTokenDto {
    'items': Array<UserWithoutTokenDto>;
    'totalItems': PaginatedResponseDtoOfCommentDtoTotalItems;
    'totalPages': PaginatedResponseDtoOfCommentDtoTotalItems;
    'currentPage': PaginatedResponseDtoOfCommentDtoTotalItems;
    'pageSize': PaginatedResponseDtoOfCommentDtoTotalItems;
}
export interface RegisterDto {
    'userName': string;
    'email': string;
    'password': string;
}
export interface SearchAccountsPageNumberParameter {
}
export interface SearchAccountsPageSizeParameter {
}
export interface SearchCommentsParentIdParameter {
}
export interface UpdateCommentDto {
    'content': string;
}
export interface UpdateUserDto {
    'userName'?: string | null;
    'email'?: string | null;
}

export const UserDevRole = {
    Reader: 'Reader',
    Commentor: 'Commentor',
    Editor: 'Editor',
    Administrator: 'Administrator',
} as const;

export type UserDevRole = typeof UserDevRole[keyof typeof UserDevRole];


export interface UserWithTokenDto {
    'id': string;
    'userName': string;
    'email': string;
    'token': string;
}
export interface UserWithoutTokenDto {
    'id': string;
    'userName': string;
}

/**
 * AccountApi - axios parameter creator
 */
export const AccountApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login: async (loginDto: LoginDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'loginDto' is not null or undefined
            assertParamExists('login', 'loginDto', loginDto)
            const localVarPath = `/api/accounts/login`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(loginDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {RegisterDto} registerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register: async (registerDto: RegisterDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'registerDto' is not null or undefined
            assertParamExists('register', 'registerDto', registerDto)
            const localVarPath = `/api/accounts/register`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(registerDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [userName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAccounts: async (pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, userName?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageNumber !== undefined) {
                localVarQueryParameter['PageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }

            if (userName !== undefined) {
                localVarQueryParameter['userName'] = userName;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccountInfo: async (updateUserDto: UpdateUserDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'updateUserDto' is not null or undefined
            assertParamExists('updateAccountInfo', 'updateUserDto', updateUserDto)
            const localVarPath = `/api/accounts`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccountApi - functional programming interface
 */
export const AccountApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccountApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async login(loginDto: LoginDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserWithTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.login(loginDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.login']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {RegisterDto} registerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async register(registerDto: RegisterDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserWithTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.register(registerDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.register']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [userName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchAccounts(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, userName?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDtoOfUserWithoutTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchAccounts(pageNumber, pageSize, userName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.searchAccounts']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateAccountInfo(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserWithTokenDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateAccountInfo(updateUserDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccountApi.updateAccountInfo']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccountApi - factory interface
 */
export const AccountApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccountApiFp(configuration)
    return {
        /**
         * 
         * @param {LoginDto} loginDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        login(loginDto: LoginDto, options?: RawAxiosRequestConfig): AxiosPromise<UserWithTokenDto> {
            return localVarFp.login(loginDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {RegisterDto} registerDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        register(registerDto: RegisterDto, options?: RawAxiosRequestConfig): AxiosPromise<UserWithTokenDto> {
            return localVarFp.register(registerDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [userName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchAccounts(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, userName?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDtoOfUserWithoutTokenDto> {
            return localVarFp.searchAccounts(pageNumber, pageSize, userName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {UpdateUserDto} updateUserDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateAccountInfo(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig): AxiosPromise<UserWithTokenDto> {
            return localVarFp.updateAccountInfo(updateUserDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AccountApi - object-oriented interface
 */
export class AccountApi extends BaseAPI {
    /**
     * 
     * @param {LoginDto} loginDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public login(loginDto: LoginDto, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).login(loginDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {RegisterDto} registerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public register(registerDto: RegisterDto, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).register(registerDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SearchAccountsPageNumberParameter} [pageNumber] 
     * @param {SearchAccountsPageSizeParameter} [pageSize] 
     * @param {string} [userName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchAccounts(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, userName?: string, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).searchAccounts(pageNumber, pageSize, userName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {UpdateUserDto} updateUserDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateAccountInfo(updateUserDto: UpdateUserDto, options?: RawAxiosRequestConfig) {
        return AccountApiFp(this.configuration).updateAccountInfo(updateUserDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * CommentsApi - axios parameter creator
 */
export const CommentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearComment: async (commentId: SearchCommentsParentIdParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('clearComment', 'commentId', commentId)
            const localVarPath = `/api/comments/{commentId}`
                .replace('{commentId}', encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment: async (createCommentDto: CreateCommentDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createCommentDto' is not null or undefined
            assertParamExists('createComment', 'createCommentDto', createCommentDto)
            const localVarPath = `/api/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createCommentDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentById: async (commentId: SearchCommentsParentIdParameter, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('getCommentById', 'commentId', commentId)
            const localVarPath = `/api/comments/{commentId}`
                .replace('{commentId}', encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {SearchCommentsParentIdParameter} [parentId] 
         * @param {string} [documentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchComments: async (pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, parentId?: SearchCommentsParentIdParameter, documentId?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/comments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (pageNumber !== undefined) {
                localVarQueryParameter['PageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }

            if (parentId !== undefined) {
                localVarQueryParameter['ParentId'] = parentId;
            }

            if (documentId !== undefined) {
                localVarQueryParameter['DocumentId'] = documentId;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {UpdateCommentDto} updateCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment: async (commentId: SearchCommentsParentIdParameter, updateCommentDto: UpdateCommentDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'commentId' is not null or undefined
            assertParamExists('updateComment', 'commentId', commentId)
            // verify required parameter 'updateCommentDto' is not null or undefined
            assertParamExists('updateComment', 'updateCommentDto', updateCommentDto)
            const localVarPath = `/api/comments/{commentId}`
                .replace('{commentId}', encodeURIComponent(String(commentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateCommentDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * CommentsApi - functional programming interface
 */
export const CommentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = CommentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async clearComment(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.clearComment(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.clearComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createComment(createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createComment(createCommentDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.createComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getCommentById(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getCommentById(commentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.getCommentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {SearchCommentsParentIdParameter} [parentId] 
         * @param {string} [documentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchComments(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, parentId?: SearchCommentsParentIdParameter, documentId?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDtoOfCommentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchComments(pageNumber, pageSize, parentId, documentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.searchComments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {UpdateCommentDto} updateCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateComment(commentId: SearchCommentsParentIdParameter, updateCommentDto: UpdateCommentDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CommentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateComment(commentId, updateCommentDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['CommentsApi.updateComment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * CommentsApi - factory interface
 */
export const CommentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = CommentsApiFp(configuration)
    return {
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        clearComment(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.clearComment(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {CreateCommentDto} createCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createComment(createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig): AxiosPromise<CommentDto> {
            return localVarFp.createComment(createCommentDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getCommentById(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig): AxiosPromise<CommentDto> {
            return localVarFp.getCommentById(commentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {SearchCommentsParentIdParameter} [parentId] 
         * @param {string} [documentId] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchComments(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, parentId?: SearchCommentsParentIdParameter, documentId?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDtoOfCommentDto> {
            return localVarFp.searchComments(pageNumber, pageSize, parentId, documentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {SearchCommentsParentIdParameter} commentId 
         * @param {UpdateCommentDto} updateCommentDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateComment(commentId: SearchCommentsParentIdParameter, updateCommentDto: UpdateCommentDto, options?: RawAxiosRequestConfig): AxiosPromise<CommentDto> {
            return localVarFp.updateComment(commentId, updateCommentDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * CommentsApi - object-oriented interface
 */
export class CommentsApi extends BaseAPI {
    /**
     * 
     * @param {SearchCommentsParentIdParameter} commentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public clearComment(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).clearComment(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {CreateCommentDto} createCommentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createComment(createCommentDto: CreateCommentDto, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).createComment(createCommentDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SearchCommentsParentIdParameter} commentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getCommentById(commentId: SearchCommentsParentIdParameter, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).getCommentById(commentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SearchAccountsPageNumberParameter} [pageNumber] 
     * @param {SearchAccountsPageSizeParameter} [pageSize] 
     * @param {SearchCommentsParentIdParameter} [parentId] 
     * @param {string} [documentId] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchComments(pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, parentId?: SearchCommentsParentIdParameter, documentId?: string, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).searchComments(pageNumber, pageSize, parentId, documentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {SearchCommentsParentIdParameter} commentId 
     * @param {UpdateCommentDto} updateCommentDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateComment(commentId: SearchCommentsParentIdParameter, updateCommentDto: UpdateCommentDto, options?: RawAxiosRequestConfig) {
        return CommentsApiFp(this.configuration).updateComment(commentId, updateCommentDto, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DocumentApi - axios parameter creator
 */
export const DocumentApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocument: async (createUpdateDocDto: CreateUpdateDocDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createUpdateDocDto' is not null or undefined
            assertParamExists('createDocument', 'createUpdateDocDto', createUpdateDocDto)
            const localVarPath = `/api/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUpdateDocDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocumentById: async (docId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('deleteDocumentById', 'docId', docId)
            const localVarPath = `/api/documents/{docId}`
                .replace('{docId}', encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocumentById: async (docId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('getDocumentById', 'docId', docId)
            const localVarPath = `/api/documents/{docId}`
                .replace('{docId}', encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} [sortBy] 
         * @param {boolean} [sortAscending] 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [title] 
         * @param {Array<string>} [tags] 
         * @param {string} [fromDate] 
         * @param {string} [toDate] 
         * @param {string} [ownerName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDocuments: async (sortBy?: string, sortAscending?: boolean, pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, title?: string, tags?: Array<string>, fromDate?: string, toDate?: string, ownerName?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/documents`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (sortBy !== undefined) {
                localVarQueryParameter['SortBy'] = sortBy;
            }

            if (sortAscending !== undefined) {
                localVarQueryParameter['SortAscending'] = sortAscending;
            }

            if (pageNumber !== undefined) {
                localVarQueryParameter['PageNumber'] = pageNumber;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['PageSize'] = pageSize;
            }

            if (title !== undefined) {
                localVarQueryParameter['Title'] = title;
            }

            if (tags) {
                localVarQueryParameter['Tags'] = tags;
            }

            if (fromDate !== undefined) {
                localVarQueryParameter['FromDate'] = (fromDate as any instanceof Date) ?
                    (fromDate as any).toISOString() :
                    fromDate;
            }

            if (toDate !== undefined) {
                localVarQueryParameter['ToDate'] = (toDate as any instanceof Date) ?
                    (toDate as any).toISOString() :
                    toDate;
            }

            if (ownerName !== undefined) {
                localVarQueryParameter['OwnerName'] = ownerName;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} docId 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDocument: async (docId: string, createUpdateDocDto: CreateUpdateDocDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'docId' is not null or undefined
            assertParamExists('updateDocument', 'docId', docId)
            // verify required parameter 'createUpdateDocDto' is not null or undefined
            assertParamExists('updateDocument', 'createUpdateDocDto', createUpdateDocDto)
            const localVarPath = `/api/documents/{docId}`
                .replace('{docId}', encodeURIComponent(String(docId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUpdateDocDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DocumentApi - functional programming interface
 */
export const DocumentApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DocumentApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDocument(createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDocument(createUpdateDocDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentApi.createDocument']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDocumentById(docId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDocumentById(docId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentApi.deleteDocumentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDocumentById(docId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDocumentById(docId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentApi.getDocumentById']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} [sortBy] 
         * @param {boolean} [sortAscending] 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [title] 
         * @param {Array<string>} [tags] 
         * @param {string} [fromDate] 
         * @param {string} [toDate] 
         * @param {string} [ownerName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchDocuments(sortBy?: string, sortAscending?: boolean, pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, title?: string, tags?: Array<string>, fromDate?: string, toDate?: string, ownerName?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PaginatedResponseDtoOfDocumentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchDocuments(sortBy, sortAscending, pageNumber, pageSize, title, tags, fromDate, toDate, ownerName, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentApi.searchDocuments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} docId 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDocument(docId: string, createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DocumentDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDocument(docId, createUpdateDocDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DocumentApi.updateDocument']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DocumentApi - factory interface
 */
export const DocumentApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DocumentApiFp(configuration)
    return {
        /**
         * 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDocument(createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig): AxiosPromise<DocumentDto> {
            return localVarFp.createDocument(createUpdateDocDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDocumentById(docId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteDocumentById(docId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} docId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDocumentById(docId: string, options?: RawAxiosRequestConfig): AxiosPromise<DocumentDto> {
            return localVarFp.getDocumentById(docId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} [sortBy] 
         * @param {boolean} [sortAscending] 
         * @param {SearchAccountsPageNumberParameter} [pageNumber] 
         * @param {SearchAccountsPageSizeParameter} [pageSize] 
         * @param {string} [title] 
         * @param {Array<string>} [tags] 
         * @param {string} [fromDate] 
         * @param {string} [toDate] 
         * @param {string} [ownerName] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchDocuments(sortBy?: string, sortAscending?: boolean, pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, title?: string, tags?: Array<string>, fromDate?: string, toDate?: string, ownerName?: string, options?: RawAxiosRequestConfig): AxiosPromise<PaginatedResponseDtoOfDocumentDto> {
            return localVarFp.searchDocuments(sortBy, sortAscending, pageNumber, pageSize, title, tags, fromDate, toDate, ownerName, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} docId 
         * @param {CreateUpdateDocDto} createUpdateDocDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDocument(docId: string, createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig): AxiosPromise<DocumentDto> {
            return localVarFp.updateDocument(docId, createUpdateDocDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DocumentApi - object-oriented interface
 */
export class DocumentApi extends BaseAPI {
    /**
     * 
     * @param {CreateUpdateDocDto} createUpdateDocDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDocument(createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig) {
        return DocumentApiFp(this.configuration).createDocument(createUpdateDocDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} docId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDocumentById(docId: string, options?: RawAxiosRequestConfig) {
        return DocumentApiFp(this.configuration).deleteDocumentById(docId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} docId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDocumentById(docId: string, options?: RawAxiosRequestConfig) {
        return DocumentApiFp(this.configuration).getDocumentById(docId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} [sortBy] 
     * @param {boolean} [sortAscending] 
     * @param {SearchAccountsPageNumberParameter} [pageNumber] 
     * @param {SearchAccountsPageSizeParameter} [pageSize] 
     * @param {string} [title] 
     * @param {Array<string>} [tags] 
     * @param {string} [fromDate] 
     * @param {string} [toDate] 
     * @param {string} [ownerName] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public searchDocuments(sortBy?: string, sortAscending?: boolean, pageNumber?: SearchAccountsPageNumberParameter, pageSize?: SearchAccountsPageSizeParameter, title?: string, tags?: Array<string>, fromDate?: string, toDate?: string, ownerName?: string, options?: RawAxiosRequestConfig) {
        return DocumentApiFp(this.configuration).searchDocuments(sortBy, sortAscending, pageNumber, pageSize, title, tags, fromDate, toDate, ownerName, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} docId 
     * @param {CreateUpdateDocDto} createUpdateDocDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateDocument(docId: string, createUpdateDocDto: CreateUpdateDocDto, options?: RawAxiosRequestConfig) {
        return DocumentApiFp(this.configuration).updateDocument(docId, createUpdateDocDto, options).then((request) => request(this.axios, this.basePath));
    }
}



